# Big Data Modelling and Management 2022

Group number: 22

Students (name : student number):

1. Lucas CorrÃªa 20211006

2. Vera Canhoto: 20210659 

3. Doyun: 20200565

4. Bruna Duarte: 20210669

## ðŸšš BDMM Second Homework Assignment ðŸšš 

_The Wide World Importers (WWI) is a wholesales novelty goods importer and distributor operating from the San Francisco bay area. In this assignment we will be working with their database._ 
You can get more information and details about the WWI database in the following link: https://docs.microsoft.com/en-us/sql/samples/wide-world-importers-what-is?view=sql-server-ver15

The focus of the second assignment is modelling. We will use the World Wide Importers database and convert it to a document-based database. To that end, we will be leveraging concepts like data denormalization, indices, and mongodb design patterns. 

More information on the extended datamodel to be found here: </br>  
https://docs.microsoft.com/en-us/sql/samples/wide-world-importers-oltp-database-catalog?view=sql-server-ver15

## Problem Description

Your team has just arrived at WWI (a leading company in logistics). Welcome!   <br>
Even though business is thriving, the IT department is going through a bad time.   <br>
Digitalization was never a priority for the company and now the company operational and analytical requirements are starting to grow beyond the capabilities of their existing data architecture.   <br>

WWI data are spread accross different systems, but we've already managed to pull them all into a mongo dump file. This data file is an exact dump of the SQL data so includes all the same structure, the SQL tables become collections and the rows become documents. This means all the original SQL keys are included in the data.<br>
Currently, the costs to develop the necessary queries to collect data to answer questions asked by the different departments are too high. <br>

Management concluded it is the right time to revise and revamp the data architecture, in order to speed up operations. 

In that context, your team was tasked with merging all the company data into a single and coherent Mongo database. <br>
It is expected that, with your solution, WWI will have a better understanding of their business and that the different departments will be able to obtain efficiently the answers they need.

The WWI team shared with you an ERD of their current datamodel:<br>
![datamodel](./WWI.png)

**Note** You can open the file WWI.png that is in the same directory as this notebook to see the above image in more detail and zoom in as you need.

Addtionally, the WWI team asked you the deliver the following outputs in **4 weeks**:
- Understand and model the database in MongoDB.
- Setup the database so that it is performs well for the queries they have provided. You should include reasoning in comments for the decisions you make on modelling the database.
- Answer the questions (queries) on the data provided.  
- Submit the results by following the instructions.  

With these deliveries, you will have created a prototype and allows the management to decide whether MongoDB is a good solution that meets their requirements.

### Design Requirements

Note that WWI has the following query requirements for the database.

1. The web team needs to know:  
    1. Which state province do we have the most suppliers in?  
    2. How many people have three or more `OtherLanguage`? 
    3. Top 10 most common `OtherLanguage` for people records. 
    4. How many customer records are valid after `November 2015`? 
    5. What percentage of people records don't have the UserPreferences field? 

2. The warehouse group needs to know:  
    1. What is the average difference in days between OrderDate and ExpectedDeliveryDate for orders sold by (`SalespersonPersonID`) person with the name `Jack Potter`?
    2. Which items get ordered the most in bulk (largest average quantity ordered)?  
    3. Which two items get ordered together the most?
    4. For each customer category which 3 items have the ordered the most?
    5. What is the current stock of each stockgroup?

3. The CFO needs to know:  
    1. What is the monthly total order count for each month?  
    2. How many orders are there from the customer `Tailspin Toys (Head Office)`?
    3. What are the average monthly sales prices of all goods sold? 
    4. In each state province what is the average customer credit limit?   
    5. What are the yearly expenditures with each supplier (per supplier name)?  

4. Partnerships needs to know:  
    1. What is the most common payment type?  
    2. What percentage of people have their `Title` as `Team Member`?
    3. Which supplier of the category `Novelty Goods Supplier` has the most transactions?  
    4. What is the highest `CommissionRate` that a person has?

5. The marketing team needs to know:  
    1. What is the name of the sales person with the largest sum of invoice values in 2013 (person whose customers paid the most money)?
    2. Who are the most common `PickedByPersonID` person names for orders done by customer `Adriana Pena`?
    3. How many people have in their name the string `Sara`?
    5. What are the top 10 most Common Names (Primary or Surnames) of people?

Transform the mongo dump file provided with this notebook and model a database following mongodb's best practices. You should adjust the data model to best fit the use cases provided above. Think about collections, embedding, linking, indexing, and the patterns learned in class. Provide justifications for each decision you make. What, if any, are the trade-off's or disadvantages of your approach.

Use MongoDB queries to answer the questions on your transformed database.

### Deliverables

1. Notebook with all DB creation operations and CRUD operations to create the data model. **Important** you should include in comments justification for your decisions on modelling the data.;
2. Second notebook with all required queries and answers for the questions, **Important** please indicate with comments the steps in the data model you took to optimise each query;

# Additional Information

## Groups  

Students should form groups of at least 4 and at most 5. <br>

## Submission  Deadline

The submission includes two notebooks with outputs (cells must be run). 
Please make sure to indicate:
1. group number,
2. group members with student names and numbers,
3. the name of the database that you created. <br>

Upload the notebook on moodle before **23:59 on June 22nd**

## Evaluation   

The second homework assignment counts 40% towards your final mark of the curricular unit. <br>
The assignment will be scored from 0 to 20. <br>

Each group submission will be evaluated on three components:
1. correctness of results;
2. simplicity and performance characteristics of the solution;
3. justification of decisions.

50% -  Database design  
50% -  Query results including performance

Please note that all code delivered in this assignment will go through plagiarism automated checks. <br>
Groups with high similarity levels in their code will undergo investigation.

* [1. Quering](#Quering)
    * [1.1 The web team needs to know](#q1)
         * [A. Which state province do we have the most suppliers in?](#q1a)
         * [B. How many people have three or more `OtherLanguage`?](#q1b)
         * [C. Top 10 most common `OtherLanguage` for people records.](#q1c)
         * [D. How many customer records are valid after `November 2015`?](#q1d)
         * [E. What percentage of people records don't have the UserPreferences field?](#q1e)
    * [1.2 The warehouse group needs to know](#q2)
         * [A. What is the average difference in days between OrderDate and ExpectedDeliveryDate for orders sold by (`SalespersonPersonID`) person with the name `Jack Potter`?](#q2a)
         * [B. Which items get ordered the most in bulk (largest average quantity ordered)?](#q2b)
         * [C. Which two items get ordered together the most?](#q2c)
         * [D. For each customer category which 3 items have the ordered the most?](#q2d)
         * [E. What is the current stock of each stockgroup?](#q2e)
    * [1.3 The CFO needs to know](#q3)
         * [A. What is the monthly total order count for each month?](#q3a)
         * [B. How many orders are there from the customer `Tailspin Toys (Head Office)`?](#q3b)
         * [C. What are the average monthly sales prices of all goods sold?](#q3c)
         * [D. In each state province what is the average customer credit limit?](#q3d)
         * [E. What are the yearly expenditures with each supplier (per supplier name)?](#q3e)
    * [1.4 Partnerships needs to know](#q4)
         * [A. What is the most common payment type?](#q4a)
         * [B. What percentage of people have their `Title` as `Team Member`?](#q4b)
         * [C. Which supplier of the category `Novelty Goods Supplier` has the most transactions?](#q4c)
         * [D. What is the highest `CommissionRate` that a person has?](#q4d)
    * [1.5 The marketing team needs to know](#q5)
         * [A. What is the name of the sales person with the largest sum of invoice values in 2013 (person whose customers paid the most money)?](#q5a)
         * [B. Who are the most common `PickedByPersonID` person names for orders done by customer `Adriana Pena`?](#q5b)
         * [C. How many people have in their name the string `Sara`?](#q5c)
         * [D. What are the top 10 most Common Names (Primary or Surnames) of people?](#q5d)

In [203]:
import pymongo
from pymongo import MongoClient
from pprint import pprint

In [204]:
protocol = "mongodb"
user = 'AzureDiamond'
password = 'hunter2'
host = 'localhost'
port = 27017
client = MongoClient(f"{protocol}://{user}:{password}@{host}:{port}/")
db = client.WideWorldImporters
print(f"Database info: {db}\n")

Database info: Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'WideWorldImporters')

<hr>
<a id="Quering">
    
# 1. Quering

    
</a>


<a id="q1">

## 1.1 The web team needs to know
    
</a>


<a id="q1a">

### A. Which state province do we have the most suppliers in?
    
</a>

In [205]:
query_1 = {
    "$lookup":{
        "from": "Suppliers_StateProvinceID_embed",
        "localField": "SupplierID",
        "foreignField": "SupplierID",
        "as": "StateProvince"
    }
}

query_2 = {"$unwind": "$StateProvince"}

query_3 = {"$group":
           {
            '_id':'$StateProvince.StateProvinceName',
            'SupplierCount':{'$sum':1}
            }
        }

sort = {'$sort':{'SupplierCount':-1}}

limit = {'$limit':1}
pipeline = [query_1, query_2, query_3,sort,limit]

r = list(db.suppliers.aggregate(pipeline))

r

[{'_id': 'California', 'SupplierCount': 3}]

<a id="q1b">

### B. How many people have three or more OtherLanguage?
    
</a>

In [206]:
# Set parameters to use $size function later
query_1b0 = {'$match':{"$and":[
    {'OtherLanguages':{'$exists': True}},
    {'OtherLanguages':{'$ne': '[]'}}, 
    {'OtherLanguages':{'$ne': None}}]
                    }}
                      
# split the strings, find the size
query_1b1 = {'$project':{'_id':False,'OtherLanguages':{'$size':{'$split':['$OtherLanguages',',']}}}}

# Set the criteria: greater or equal to 3
query_1b2 = {'$match': {'OtherLanguages' : {'$gte': 3}}}

# count the people
query_1b3 = {'$count' : 'Number of people who have three or more OtherLanguages'}

pipeline = [query_1b0, query_1b1, query_1b2, query_1b3]

r = db.people.aggregate(pipeline)

list(r)

[{'Number of people who have three or more OtherLanguages': 4}]

<a id="q1c">

### C. Top 10 most common OtherLanguage for people records.
    
</a>

In [207]:
query_1 = {'$match':
           {"$and":[
               {'OtherLanguages':{'$exists': True}},
               {'OtherLanguages':{'$ne': '[]'}}, 
               {'OtherLanguages':{'$ne': None}}]
            }}

query_2 = { '$set':
           {'ext': {'$regexFindAll': { 'input': "$OtherLanguages", 'regex': "([A-Z]\w+)" } } } 
          }

query_3 = { '$group': 
           { '_id': 'null', 
            'extensions': { '$push': "$ext.match" } 
           } 
          }

query_4 = {
        "$unwind": "$extensions"
        }

query_5 = {
        "$unwind": "$extensions"
        }

query_6 = { '$group': 
           { '_id': '$extensions', 
            'count': { '$sum': 1 } 
           } 
          }

query_7 = {'$sort' : {'count':-1}}

query_8 = {'$limit' : 10}

pipeline = [query_1,query_2,query_3,query_4,query_5,query_6,query_7,query_8]


r = list(db.people.aggregate(pipeline))

r[:10]

[{'_id': 'Dutch', 'count': 3},
 {'_id': 'Finnish', 'count': 3},
 {'_id': 'Greek', 'count': 3},
 {'_id': 'Arabic', 'count': 2},
 {'_id': 'Slovak', 'count': 2},
 {'_id': 'Lithuanian', 'count': 2},
 {'_id': 'Romanian', 'count': 2},
 {'_id': 'Polish', 'count': 2},
 {'_id': 'Croatian', 'count': 2},
 {'_id': 'Portuguese', 'count': 1}]

<a id="q1d">

### D. How many customer records are valid after November 2015?
    
</a>

In [208]:
from datetime import datetime
d = datetime(2015, 11, 1)
query_1 = {
    '$match':{'ValidFrom': {"$gte": d}}
}

query_2 = {
    '$count' : 'Number of customer records that are valid after November 2015'
}

pipeline = [query_1, query_2]

r = db.customers.aggregate(pipeline)

list(r)

[{'Number of customer records that are valid after November 2015': 9}]

<a id="q1e">

### E. What percentage of people records don't have the UserPreferences field?
    
</a>

In [209]:
query_1e0 = {
    '$match':{"$or":[
    {'UserPreferences':{'$exists': False}},
    {'UserPreferences':{'$eq': ''}}, 
    {'UserPreferences':{'$eq': None}}]
                    }
}

query_1e1 = {
    '$count' : 'UserPreferences'
}

pipeline = [query_1e0, query_1e1]

r = db.people.aggregate(pipeline)

list(r)

[{'UserPreferences': 929}]

<a id="q2">

## 1.2 The warehouse group needs to know
    
</a>

<a id="q2a">

### A. What is the average difference in days between OrderDate and ExpectedDeliveryDate for orders sold by (SalespersonPersonID) person with the name Jack Potter?
    
</a>

In [210]:
query_1 = {
        "$lookup":{
           "from": "people",
           "localField": "SalespersonPersonID",
           "foreignField": "PersonID",
           "as": "SalesPersonInfo"
        }
    }


query_2 = {
    "$unwind": "$SalesPersonInfo"
}

query_3 = {'$match': 
               {'SalesPersonInfo.FullName': 'Jack Potter'}
          }


query_4 = {'$group':
                {'_id' : '$SalesPersonInfo.FullName', 
                 'averageDiff' : {'$avg' : {'$dateDiff': {'startDate': '$OrderDate',
                                            'endDate': '$ExpectedDeliveryDate',
                                            'unit': 'day',}
                                           }
                                 } 
                }
          }

limit = {'$limit':5}

pipeline = [query_1,query_2,query_3,query_4,limit]
    
result = list(db.orders.aggregate(pipeline))

result

[{'_id': 'Jack Potter', 'averageDiff': 1.4490320833897388}]

<a id="q2b">

### B. Which items get ordered the most in bulk (largest average quantity ordered)?
    
</a>

In [211]:
query_1 = {
        '$group':
                {'_id' : '$StockItemID', # will be groupped by this field
                 'averageQtordered' : {'$avg' : '$Quantity'}
                } # type of accumulator
          }

query_2 = {
        '$sort':
            {'averageQtordered' : -1}
        } # -1 desc, 1 asc.

limit = {'$limit':5}

pipeline = [query_1,query_2,limit]
    
result = list(db.orderlines.aggregate(pipeline))

result

[{'_id': 191, 'averageQtordered': 199.35},
 {'_id': 192, 'averageQtordered': 198.23950870010236},
 {'_id': 189, 'averageQtordered': 145.26190476190476},
 {'_id': 185, 'averageQtordered': 141.64338919925513},
 {'_id': 188, 'averageQtordered': 141.48096564531104}]

<a id="q2c">

### C. Which two items get ordered together the most?
    
</a>

In [212]:
query_0 = {'$match': 
            { '$or': [ {'OrderID': 4}, {'OrderID': 5} ] }
          }

#order every order and itemID so the list of itemIDs be oredered and the combination always follow the same pattern
sort = {'$sort':
        {'OrderID' : 1,
        'StockItemID' : 1}
    } 

query_1 = {'$group': 
               {
                '_id': '$OrderID',      
                'combination': {'$push':'$StockItemID'}
               }
          }

#http://www.kamsky.org/stupid-tricks-with-mongodb/how-to-get-k-combinations-from-array-in-aggregation
query_2 = {'$project':
           {'comb':{'$reduce':{
                   'input':{'$range':[0,{'$size':"$combination"}]}, 
                   'initialValue':[], 
                   'in':{'$concatArrays':[ 
                      "$$value", 
                      {'$let':{
                         'vars':{'i':"$$this"},
                         'in':{'$map':{
                            'input':{'$range':[{'$add':[1,"$$i"]},{'$size':"$combination"}]},
                            'in':[ {'$arrayElemAt':["$combination","$$i"]}, {'$arrayElemAt':["$combination","$$this"]}] }}
                      }}
                   ]}
                }}
           }
          }

query_3 = {"$unwind": "$comb"}

query_4 = {'$group': 
               {
                '_id': '$comb',      
                'qty': {'$sum':1}
               }
          }

sort = {'$sort':
            {'qty' : -1}
            }

limit = {'$limit' : 5}

pipeline = [sort,query_1,query_2,query_3,query_4,sort,limit]

result = list(db.orderlines.aggregate(pipeline))
result

[{'_id': [167, 132], 'qty': 21},
 {'_id': [182, 45], 'qty': 20},
 {'_id': [50, 219], 'qty': 20},
 {'_id': [59, 195], 'qty': 19},
 {'_id': [214, 154], 'qty': 18}]

<a id="q2d">

### D. For each customer category which 3 items have the ordered the most?
    
</a>

In [254]:
query_0 = {"$project": 
            {'CustomerCategoryID': "$CustomerCategoryID",
             'CustomerID':'$CustomerID'
            }
        }

query_1 = {"$lookup":
           {
           "from": "orders",
           "localField": "CustomerID",
           "foreignField": "CustomerID",
           "as": "OrdersDone"
            }
        }

query_2 = {"$unwind": "$OrdersDone",
        }

query_3 = {"$unwind": "$OrdersDone.OrderItemsIDs",
        }

query_4 = {'$group':
                {
                 '_id' : {'CustomerCategoryID':'$CustomerCategoryID','itemID':'$OrdersDone.OrderItemsIDs'}, 
                 'count' : {'$sum': 1}
                } 
          }

query_5 = {'$sort':
            {'count' : -1}
          } 

query_6 = {'$group':
                {'_id' : '$_id.CustomerCategoryID', 
                 'ordersArray' : {'$push':  { 'itemID':'$_id.itemID','count':'$count' } }
                }
        } 
          

query_7 = { '$project': 
           {'CustomerCategoryID': '$_id', 
            'top3': { '$slice': [ "$ordersArray", 3 ] } } 
          }

pipeline = [query_0,query_1,query_2,query_3,query_4,query_5,query_6,query_7]

r = list(db.customers.aggregate(pipeline))

r[:3]

[{'_id': 5,
  'CustomerCategoryID': 5,
  'top3': [{'itemID': 104, 'count': 98},
   {'itemID': 200, 'count': 94},
   {'itemID': 72, 'count': 94}]},
 {'_id': 6,
  'CustomerCategoryID': 6,
  'top3': [{'itemID': 76, 'count': 95},
   {'itemID': 80, 'count': 91},
   {'itemID': 5, 'count': 89}]},
 {'_id': 4,
  'CustomerCategoryID': 4,
  'top3': [{'itemID': 100, 'count': 110},
   {'itemID': 88, 'count': 106},
   {'itemID': 108, 'count': 104}]}]

<a id="q2e">

### E. What is the current stock of each stockgroup?
    
</a>

In [214]:
query_1 = {
        "$lookup":{
           "from": "stockitemsstockgroups",
           "localField": "StockItemID",
           "foreignField": "StockItemID",
           "as": "stockItemgroup"
        }
    }

query_2 = {
        "$unwind": "$stockItemgroup"
        }

query_0 = {'$match': 
               {'stockItemgroup.StockGroupID': 9}
          }

query_3 = { '$group': 
           {'_id': '$stockItemgroup.StockGroupID', 
            'StockItemID': { '$push': '$stockItemgroup.StockItemID' } } 
          }

query_4 = {
        "$lookup":{
           "from": "invoicelines",
           "localField": "StockItemID",
           "foreignField": "StockItemID",
           "as": "stockOutcoming"
        }
    }

query_5 = {
        "$unwind": "$stockOutcoming"
        }

query_6 = { '$group': 
           {'_id': {'GroupId':'$_id', 'StockItemID':'$StockItemID'}, 
            'stockOUT': { '$sum': '$stockOutcoming.Quantity' },
            } 
          }

query_7 = {
        "$lookup":{
           "from": "purchaseorderlines",
           "localField": "_id.StockItemID",
           "foreignField": "StockItemID",
           "as": "stockIncoming"
        }
    }

query_8 = {
        "$unwind": "$stockIncoming"
        }

query_9 = { '$group': 
           {'_id': {'GroupId':'$_id.GroupId', 'StockItemID': '$_id.StockItemID','stockOUT':'$stockOUT'}, 
            'stockIN': { '$sum': '$stockIncoming.ReceivedOuters' }} 
          }

query_10 = {'$project':{'$_id.GroupId':1,}}
pipeline = [query_1,query_2,query_3,query_4,query_5,query_6,query_7,query_8,query_9]
    
result = list(db.stockitems.aggregate(pipeline))

result

[{'_id': {'GroupId': 4,
   'StockItemID': [76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101],
   'stockOUT': 1581492},
  'stockIN': 7576727},
 {'_id': {'GroupId': 10,
   'StockItemID': [153,
    154,
    155,
    156,
    157,
    158,
    159,
    160,
    161,
    162,
    163,
    164,
    165,
    166,
    167,
    168,
    169,
    170,
    171,
    172,
    173,
    174,
    175,
    176,
    177,
    178,
    179,
    180,
    181,
    182,
    183,
    184,
    185,
    186,
    187,
    188,
    189,
    190,
    191,
    192,
    193,
    194,
    195,
    196,
    197,
    198,
    199,
    200,
    201,
    202,
    203,
    204,
    205,
    206,
    207,
    208,
    209,
    210,
    211,
    212,
    213,
    214,
    215,
    216,
    217,
    218,
    219],
   'stockOUT': 5696347},
  'stockIN': 2702432},
 {'_id': {'GroupId': 3,
   'StockItemID': [16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57],
   'stockOUT': 244010},
  'stockIN': 1442},
 {'_id': {'GroupId': 2,
   'StockItemID': [76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
    123,
    124,
    125,
    126,
    127,
    128,
    129,
    130,
    131,
    132,
    133,
    134,
    135,
    136,
    137,
    138,
    139,
    140,
    141,
    142,
    143,
    144,
    145,
    146,
    147,
    148,
    149],
   'stockOUT': 2624338},
  'stockIN': 7577583},
 {'_id': {'GroupId': 1,
   'StockItemID': [1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    142,
    143,
    144,
    145,
    146,
    147,
    148,
    149,
    220,
    221,
    222,
    223,
    224,
    225,
    226,
    227],
   'stockOUT': 1168276},
  'stockIN': 4638},
 {'_id': {'GroupId': 6,
   'StockItemID': [1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101],
   'stockOUT': 1962719},
  'stockIN': 7579764},
 {'_id': {'GroupId': 9,
   'StockItemID': [58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    150,
    151,
    152],
   'stockOUT': 121360},
  'stockIN': 1313},
 {'_id': {'GroupId': 8,
   'StockItemID': [118,
    119,
    120,
    121,
    122,
    123,
    124,
    125,
    126,
    127,
    128,
    129,
    130,
    131,
    132,
    133,
    134,
    135,
    136,
    137,
    138,
    139,
    140,
    141],
   'stockOUT': 395849},
  'stockIN': 587},
 {'_id': {'GroupId': 7,
   'StockItemID': [1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
   'stockOUT': 81057},
  'stockIN': 1580}]

<a id="q3">

## 1.3 The CFO needs to know
    
</a>

<a id="q3a">

### A.  What is the monthly total order count for each month?
    
</a>

In [215]:
query_1 = {
    '$project': {
        '_id' : False,
        'OrderID': True,
        'Month': {'$month': "$OrderDate"} 
    }}


query_2 = {
    '$group': {
        '_id': '$Month',
        'OrderID' : {'$sum' : 1}  
    }
}

query_3 = {
    '$sort':
        {'_id' : 1}} 


pipeline = [query_1,query_2,query_3]

r = db.orders.aggregate(pipeline)
pprint(list(r))

[{'OrderID': 7239, '_id': 1},
 {'OrderID': 6115, '_id': 2},
 {'OrderID': 7129, '_id': 3},
 {'OrderID': 7497, '_id': 4},
 {'OrderID': 7722, '_id': 5},
 {'OrderID': 5551, '_id': 6},
 {'OrderID': 6167, '_id': 7},
 {'OrderID': 4908, '_id': 8},
 {'OrderID': 5319, '_id': 9},
 {'OrderID': 5504, '_id': 10},
 {'OrderID': 5014, '_id': 11},
 {'OrderID': 5430, '_id': 12}]

<a id="q3b">

### B.  How many orders are there from the customer Tailspin Toys (Head Office)?   'Tailspin Toys (Head Office)'  'CustomerName'
    
</a>

In [216]:
query_1 = {
    '$match': {
        'CustomerName': 'Tailspin Toys (Head Office)'
    }}


query_2 = {
        "$lookup":{
           "from": "orders",
           "localField": "CustomerID",
           "foreignField": "CustomerID",
           "as": "Orders"
        }
    }

query_3 = {
    "$unwind": "$Orders"
}


query_4 = {
    '$project': {
        '_id' : False,
        'CustomerName': True,
        'Orders': True,
    }}


#limit = {
#    "$limit": 2
#}

query_5 = {
    '$group': {
        '_id': '$CustomerName',
        'Orders' : {'$sum' : 1}  
    }
}


#query_6 = {
#'$count': 'Orders count'
   

pipeline = [query_1, query_2, query_3, query_4, query_5]

r = db.customers.aggregate(pipeline)
pprint(list(r))

[{'Orders': 129, '_id': 'Tailspin Toys (Head Office)'}]

<a id="q3c">

### C.  What are the average monthly sales prices of all goods sold?
    
</a>

In [217]:

query_0 = {
    '$project': {
        '_id' : False,
        'Description': True,
        'UnitPrice': True,
        'PickedQuantity': True,
        'LastEditedWhen': True
    }}


query_1 = {
    '$project': {
        '_id' : False,
        'Description': True,
        'TotalPrice' : {'$multiply':['$UnitPrice','$PickedQuantity']},
        'Month': {'$month': "$LastEditedWhen"} 
    }}

 
query_2 = {
    '$group':
        {'_id' : '$Month', 
         'averagePrice' : {'$avg' :'$TotalPrice'}}}


query_3 = {
    '$project': {
        '_id' : True,
        'averagePrice' : {'$round':['$averagePrice',2]}
        
    }}


query_4 = {
    '$sort':
        {'_id' : 1}} 

pipeline = [query_1, query_2, query_3, query_4]

r = db.orderlines.aggregate(pipeline)
pprint(list(r))

[{'_id': 1, 'averagePrice': Decimal128('735.19')},
 {'_id': 2, 'averagePrice': Decimal128('748.09')},
 {'_id': 3, 'averagePrice': Decimal128('747.02')},
 {'_id': 4, 'averagePrice': Decimal128('757.26')},
 {'_id': 5, 'averagePrice': Decimal128('759.71')},
 {'_id': 6, 'averagePrice': Decimal128('739.02')},
 {'_id': 7, 'averagePrice': Decimal128('744.55')},
 {'_id': 8, 'averagePrice': Decimal128('750.81')},
 {'_id': 9, 'averagePrice': Decimal128('742.45')},
 {'_id': 10, 'averagePrice': Decimal128('725.51')},
 {'_id': 11, 'averagePrice': Decimal128('745.40')},
 {'_id': 12, 'averagePrice': Decimal128('729.28')}]

<a id="q3d">

###  D.  In each state province what is the average customer credit limit?
    
</a>

In [218]:
query_7 = {
        "$lookup":{
           "from": "stateprovinces",
           "localField": "StateProvinceID",
           "foreignField": "StateProvinceID",
           "as": "Stateprovinces"
        }
    }

query_8 = {
    "$unwind": "$Stateprovinces"
}

 
query_9 = {
    '$group':
        {'_id' : '$Stateprovinces.StateProvinceName', 
         'Avarege_CreditLimit' : {'$avg' : '$CreditLimit'}}} 



query_10 = {
    '$project': {
        '_id' : True,
        'Avarege_CreditLimit' : {'$round':['$Avarege_CreditLimit',2]}
        
    }}

query_11 = {
    '$sort':
        {'_id' : 1}} 

pipeline = [query_7, query_8, query_9, query_10, query_11]

r = db.Customers_StateProvinceID_embed.aggregate(pipeline)
pprint(list(r))

[{'Avarege_CreditLimit': Decimal128('1985.00'), '_id': 'Alabama'},
 {'Avarege_CreditLimit': Decimal128('2858.33'), '_id': 'Alaska'},
 {'Avarege_CreditLimit': Decimal128('2950.00'), '_id': 'Arizona'},
 {'Avarege_CreditLimit': Decimal128('3044.17'), '_id': 'Arkansas'},
 {'Avarege_CreditLimit': Decimal128('2787.31'), '_id': 'California'},
 {'Avarege_CreditLimit': Decimal128('2033.33'), '_id': 'Colorado'},
 {'Avarege_CreditLimit': Decimal128('3500.00'), '_id': 'Connecticut'},
 {'Avarege_CreditLimit': Decimal128('2800.00'), '_id': 'Florida'},
 {'Avarege_CreditLimit': Decimal128('2631.75'), '_id': 'Georgia'},
 {'Avarege_CreditLimit': None, '_id': 'Hawaii'},
 {'Avarege_CreditLimit': Decimal128('2700.00'), '_id': 'Idaho'},
 {'Avarege_CreditLimit': Decimal128('2336.00'), '_id': 'Illinois'},
 {'Avarege_CreditLimit': Decimal128('3098.75'), '_id': 'Indiana'},
 {'Avarege_CreditLimit': Decimal128('2481.67'), '_id': 'Iowa'},
 {'Avarege_CreditLimit': Decimal128('2900.00'), '_id': 'Kansas'},
 {'Avarege_CreditLimit': Decimal128('2374.00'), '_id': 'Kentucky'},
 {'Avarege_CreditLimit': Decimal128('2372.04'), '_id': 'Louisiana'},
 {'Avarege_CreditLimit': Decimal128('2400.00'), '_id': 'Maine'},
 {'Avarege_CreditLimit': Decimal128('1750.00'), '_id': 'Maryland'},
 {'Avarege_CreditLimit': Decimal128('2507.50'), '_id': 'Massachusetts[E]'},
 {'Avarege_CreditLimit': Decimal128('2773.33'), '_id': 'Michigan'},
 {'Avarege_CreditLimit': Decimal128('2513.12'), '_id': 'Minnesota'},
 {'Avarege_CreditLimit': Decimal128('2400.00'), '_id': 'Mississippi'},
 {'Avarege_CreditLimit': Decimal128('2613.33'), '_id': 'Missouri'},
 {'Avarege_CreditLimit': Decimal128('1666.67'), '_id': 'Montana'},
 {'Avarege_CreditLimit': Decimal128('2595.00'), '_id': 'Nebraska'},
 {'Avarege_CreditLimit': Decimal128('3600.00'), '_id': 'Nevada'},
 {'Avarege_CreditLimit': Decimal128('2800.00'), '_id': 'New Hampshire'},
 {'Avarege_CreditLimit': Decimal128('2641.43'), '_id': 'New Jersey'},
 {'Avarege_CreditLimit': Decimal128('2741.00'), '_id': 'New Mexico'},
 {'Avarege_CreditLimit': Decimal128('2758.93'), '_id': 'New York'},
 {'Avarege_CreditLimit': Decimal128('2661.36'), '_id': 'North Carolina'},
 {'Avarege_CreditLimit': Decimal128('2500.00'), '_id': 'North Dakota'},
 {'Avarege_CreditLimit': Decimal128('2942.86'), '_id': 'Ohio'},
 {'Avarege_CreditLimit': Decimal128('2806.00'), '_id': 'Oklahoma'},
 {'Avarege_CreditLimit': Decimal128('3530.00'), '_id': 'Oregon'},
 {'Avarege_CreditLimit': Decimal128('2255.83'), '_id': 'Pennsylvania'},
 {'Avarege_CreditLimit': Decimal128('2766.67'),
  '_id': 'Puerto Rico (US Territory)'},
 {'Avarege_CreditLimit': Decimal128('2479.17'), '_id': 'South Carolina'},
 {'Avarege_CreditLimit': Decimal128('2747.50'), '_id': 'South Dakota'},
 {'Avarege_CreditLimit': Decimal128('3465.00'), '_id': 'Tennessee'},
 {'Avarege_CreditLimit': Decimal128('2312.50'), '_id': 'Texas'},
 {'Avarege_CreditLimit': Decimal128('3200.00'), '_id': 'Utah'},
 {'Avarege_CreditLimit': Decimal128('2000.00'), '_id': 'Vermont'},
 {'Avarege_CreditLimit': Decimal128('2915.00'), '_id': 'Virginia'},
 {'Avarege_CreditLimit': Decimal128('2520.00'), '_id': 'Washington'},
 {'Avarege_CreditLimit': Decimal128('2567.86'), '_id': 'West Virginia'},
 {'Avarege_CreditLimit': Decimal128('2133.33'), '_id': 'Wisconsin'},
 {'Avarege_CreditLimit': Decimal128('3365.00'), '_id': 'Wyoming'}]

<a id="q3e">

### E.  What are the yearly expenditures with each supplier (per supplier name)?
    
</a>

In [219]:
query_1 = {
        "$lookup":{
           "from": "suppliers",
           "localField": "SupplierID",
           "foreignField": "SupplierID",
           "as": "Suppliers"
        }
    }


query_2 = {
    "$project": {
        "SupplierName": '$Suppliers.SupplierName',
        "TransactionAmount": 1,
        'Year': {'$year': "$TransactionDate"} 
    } }
 
query_3 = {
    '$group':
        {'_id':{'Year':"$Year", 'SupplierName':"$SupplierName"}, 
         'Total_Expenditure' : {'$sum' :{ '$round' : [ '$TransactionAmount', 2] }}}}


query_4 = {
    '$sort':
        {'_id' : 1}} 


pipeline = [query_1, query_2, query_3, query_4]

r = db.suppliertransactions.aggregate(pipeline)
pprint(list(r))

[{'Total_Expenditure': Decimal128('0.00'),
  '_id': {'SupplierName': ['Contoso, Ltd.'], 'Year': 2013}},
 {'Total_Expenditure': Decimal128('485380.50'),
  '_id': {'SupplierName': ['Fabrikam, Inc.'], 'Year': 2013}},
 {'Total_Expenditure': Decimal128('0.00'),
  '_id': {'SupplierName': ['Graphic Design Institute'], 'Year': 2013}},
 {'Total_Expenditure': Decimal128('119343.32'),
  '_id': {'SupplierName': ['Litware, Inc.'], 'Year': 2013}},
 {'Total_Expenditure': Decimal128('0.00'),
  '_id': {'SupplierName': ['Northwind Electric Cars'], 'Year': 2013}},
 {'Total_Expenditure': Decimal128('0.00'),
  '_id': {'SupplierName': ['The Phone Company'], 'Year': 2013}},
 {'Total_Expenditure': Decimal128('1510955.10'),
  '_id': {'SupplierName': ['Fabrikam, Inc.'], 'Year': 2014}},
 {'Total_Expenditure': Decimal128('686937.21'),
  '_id': {'SupplierName': ['Litware, Inc.'], 'Year': 2014}},
 {'Total_Expenditure': Decimal128('2837528.40'),
  '_id': {'SupplierName': ['Fabrikam, Inc.'], 'Year': 2015}},
 {'Total_Expenditure': Decimal128('1353734.69'),
  '_id': {'SupplierName': ['Litware, Inc.'], 'Year': 2015}},
 {'Total_Expenditure': Decimal128('0.00'),
  '_id': {'SupplierName': ['A Datum Corporation'], 'Year': 2016}},
 {'Total_Expenditure': Decimal128('-2961969.90'),
  '_id': {'SupplierName': ['Fabrikam, Inc.'], 'Year': 2016}},
 {'Total_Expenditure': Decimal128('-1310231.11'),
  '_id': {'SupplierName': ['Litware, Inc.'], 'Year': 2016}}]

<a id="q4">

## 1.4 Partnerships needs to know
    
</a>

<a id="q4a">

### A.  What is the most common payment type? 
    
</a>

In [220]:
query_1 = {
        "$lookup":{
           "from": "paymentmethods",
           "localField":'PaymentMethodID', 
           "foreignField": "PaymentMethodID",
           "as": "Paymentmethods"
        }
    }

query_2 = {
    "$unwind": "$Paymentmethods"
}


query_3 = {
    '$project': {
        'CustomerID' : 1,
        'PaymentMethodName':'$Paymentmethods.PaymentMethodName'
}
        
    }


query_4 = {
    '$group': {
        '_id': '$PaymentMethodName',
        'Orders' : {'$sum' : 1}  
    }
}

   

query_5 = {
    '$sort':
        {'Count' :-1}} 


pipeline = [query_1, query_2, query_3,query_4, query_5]

r = db.customertransactions.aggregate(pipeline)

pprint(list(r))

[{'Orders': 26637, '_id': 'EFT'}]

<a id="q4b">

### B.  What percentage of people have their `Title` as `Team Member`?
    
</a>

In [230]:
#studio 3t
#db.people.find({}).forEach(function (el){el.CustomFields=JSON.parse(el.CustomFields);db.people.save(el)});
#db.getCollection("people").find({})

docs = db.people.count_documents({})

teamdocs = db.people.count_documents({"CustomFields.Title":"Team Member"})

percentage = teamdocs/docs*100

pprint(percentage)

1.17011701170117

<a id="q4c">

### C.  Which supplier of the category `Novelty Goods Supplier` has the most transactions? 
    
</a>

In [195]:
list(db.suppliertransactions.aggregate([
    {"$lookup": {
        "from": "suppliers",
        "localField": "SupplierID",
        "foreignField": "SupplierID",
        "as": "supplier"
    }},
    
    {"$lookup": {
        "from": "suppliercategories",
        "localField": "supplier.SupplierCategoryID",
        "foreignField": "SupplierCategoryID",
        "as": "suppliercategory"
    }},
    
    {"$match": {"suppliercategory.SupplierCategoryName": "Novelty Goods Supplier" }
    },
    
    {"$group": {
        "_id": "$supplier.SupplierName", 
        "count":{"$sum":1},
    }},

]))

[{'_id': ['The Phone Company'], 'count': 7},
 {'_id': ['A Datum Corporation'], 'count': 7},
 {'_id': ['Contoso, Ltd.'], 'count': 2},
 {'_id': ['Graphic Design Institute'], 'count': 16}]

<a id="q4d">

### D.  What is the highest `CommissionRate` that a person has?
    
</a>

In [232]:
list(db.people.find({},{'CustomFields.CommissionRate':1,'_id':0} ).sort('CustomFields.CommissionRate',-1).limit(1))

[{'CustomFields': {'CommissionRate': '4.55'}}]

<a id="q5">

## 1.5 The marketing team needs to know
    
</a>

<a id="q5a">

### A.  What is the name of the sales person with the largest sum of invoice values in 2013 (person whose customers paid the most money)?
    
</a>

In [236]:
query_1 = {"$project": {
                "_id":0,
                "supplierdetails.SupplierName":1,
                "TransactionAmount":1,
                'TransactionYear': {
                    "$year":"$TransactionDate"}
                        }
           }

query_2 = {"$group": {
                "_id": {
                    "Supplier":"$supplierdetails.SupplierName",
                    "Year": '2013'                    
                    },
                "Total": {
                    "$sum":"$TransactionAmount"}
                    }
           }

sort = {"$sort": {
            "Total":-1}
       }

limit = {'$limit': 1}
pipeline = [query_1, query_2, sort, limit]

r = db.SuppliersTransactionsDetails.aggregate(pipeline)
pprint(list(r))

# Answer: Name of the Supplier: Fabrikam, Inc.

[{'Total': Decimal128('1871894.10'),
  '_id': {'Supplier': 'Fabrikam, Inc.', 'Year': '2013'}}]

<a id="q5b">

### B.  Who are the most common `PickedByPersonID` person names for orders done by customer `Adriana Pena`?
    
</a>

In [246]:
query_7 = {
        "$lookup":{
           "from": "people",
           "localField":'PickedByPersonID', 
           "foreignField": "PersonID",
           "as": "People"
        }
    }

query_8 = {
    "$unwind": "$People"
}


query_9 = {
    '$project': {
        'CustomerName' : 1,
        'PickedBy_PersonName':'$People.FullName'
}
        
    }


query_10 = {
    '$group':
        {'_id': {'PickedBy_PersonName' : '$PickedBy_PersonName'},
         'Count' : {'$sum' : 1}
}
    } 

query_11 = {
    '$sort':
        {'Count' :-1}} 


pipeline = [query_7,query_8,query_9,query_10,query_11]

r = db.Customers_Orders_PickedByPersonID_embed.aggregate(pipeline)
pprint(list(r))

[{'Count': 3, '_id': {'PickedBy_PersonName': 'Piper Koch'}},
 {'Count': 3, '_id': {'PickedBy_PersonName': 'Katie Darwin'}},
 {'Count': 3, '_id': {'PickedBy_PersonName': 'Anthony Grosse'}},
 {'Count': 2, '_id': {'PickedBy_PersonName': 'Isabella Rupp'}},
 {'Count': 2, '_id': {'PickedBy_PersonName': 'Henry Forlonge'}},
 {'Count': 1, '_id': {'PickedBy_PersonName': 'Amy Trefl'}},
 {'Count': 1, '_id': {'PickedBy_PersonName': 'Taj Shand'}},
 {'Count': 1, '_id': {'PickedBy_PersonName': 'Alica Fatnowna'}},
 {'Count': 1, '_id': {'PickedBy_PersonName': 'Archer Lamble'}},
 {'Count': 1, '_id': {'PickedBy_PersonName': 'Eva Muirden'}},
 {'Count': 1, '_id': {'PickedBy_PersonName': 'Ethan Onslow'}}]

<a id="q5c">

### C.  How many people have in their name the string `Sara`?
    
</a>

In [199]:
import re

pat = re.compile(r'Sara', re.I)

query_1 = {
    '$match': {
        'FullName': {'$regex': pat}}
    }

query_2 = {
    '$group': {
        '_id': {'FullName' : '$FullName'}, 
        'Count' : {'$sum' : 1}            
    }
}


pipeline = [query_1, query_2]

r = db.people.aggregate(pipeline)

pprint(len(list(r)))

6

<a id="q5d">

### D.  What are the top 10 most Common Names (Primary or Surnames) of people?
    
</a>

In [227]:
query_1 = { '$project' : { 'name' : { '$split': ["$FullName", " "] } } }

query_2 = { '$unwind' : "$name" }

query_3 = { '$group': 
           { '_id': '$name', 
            'qty': { '$sum': 1 } 
           } 
          }

query_4 = {"$sort":  
           {"qty" : -1}
        }

query_5 = { '$match' : {'_id':{'$ne': ''}} }

limit = {'$limit' : 10}

pipeline = [query_1,query_2,query_3,query_4,query_5,limit]

r = list(db.people.aggregate(pipeline))

r

[{'_id': 'Bose', 'qty': 8},
 {'_id': 'Ganguly', 'qty': 7},
 {'_id': 'Thakur', 'qty': 6},
 {'_id': 'Roman', 'qty': 6},
 {'_id': 'PrabhupÃ„\x81da', 'qty': 5},
 {'_id': 'Dhanishta', 'qty': 5},
 {'_id': 'De', 'qty': 5},
 {'_id': 'Mukherjee', 'qty': 5},
 {'_id': 'Van', 'qty': 5},
 {'_id': 'David', 'qty': 5}]